extend type Query {
  """
  ✨ Look up a single `Invitation` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  invitation(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: Invitation_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: Invitation_FirstRow
  ): Invitation @fdc_generated(from: "Invitation", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `MinecraftServer` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  minecraftServer(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: MinecraftServer_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: MinecraftServer_FirstRow
  ): MinecraftServer @fdc_generated(from: "MinecraftServer", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ServerAccess` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  serverAccess(
    """
    The key used to identify the object.
    """
    key: ServerAccess_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ServerAccess_FirstRow
  ): ServerAccess @fdc_generated(from: "ServerAccess", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `ServerLog` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  serverLog(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: ServerLog_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: ServerLog_FirstRow
  ): ServerLog @fdc_generated(from: "ServerLog", purpose: QUERY_SINGLE)
  """
  ✨ Look up a single `User` based on `id`, `key` or `first` and return selected fields (or `null` if not found).
  """
  user(
    """
    The unique ID of the object.
    """
    id: UUID

    """
    The key used to identify the object.
    """
    key: User_Key

    """
    Fetch the first row based on the filters and ordering.
    """
    first: User_FirstRow
  ): User @fdc_generated(from: "User", purpose: QUERY_SINGLE)
  """
  ✨ List `Invitation` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  invitations(
    """
    Filter condition to narrow down the query results.
    """
    where: Invitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Invitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Invitation_Having
  ): [Invitation!]! @fdc_generated(from: "Invitation", purpose: QUERY_MULTIPLE)
  """
  ✨ List `MinecraftServer` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  minecraftServers(
    """
    Filter condition to narrow down the query results.
    """
    where: MinecraftServer_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MinecraftServer_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MinecraftServer_Having
  ): [MinecraftServer!]! @fdc_generated(from: "MinecraftServer", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ServerAccess` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  serverAccesses(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerAccess_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerAccess_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerAccess_Having
  ): [ServerAccess!]! @fdc_generated(from: "ServerAccess", purpose: QUERY_MULTIPLE)
  """
  ✨ List `ServerLog` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  serverLogs(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerLog_Having
  ): [ServerLog!]! @fdc_generated(from: "ServerLog", purpose: QUERY_MULTIPLE)
  """
  ✨ List `User` objects in the table and return selected fields, optionally filtered by `where` conditions
  """
  users(
    """
    Filter condition to narrow down the query results.
    """
    where: User_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [User_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: User_Having
  ): [User!]! @fdc_generated(from: "User", purpose: QUERY_MULTIPLE)
}
