extend type Invitation {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "Invitation", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `Invitation` table.
  """
  _count: Int! @fdc_generated(from: "Invitation.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `expiresAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  expiresAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.expiresAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `invitedById` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  invitedById_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.invitedById", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `invitedToId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  invitedToId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.invitedToId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `serverId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  serverId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.serverId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `Invitation` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "Invitation.status", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `Invitation` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "Invitation.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `expiresAt` field in the `Invitation` table.
  """
  expiresAt_min: Timestamp @fdc_generated(from: "Invitation.expiresAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `Invitation` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "Invitation.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `expiresAt` field in the `Invitation` table.
  """
  expiresAt_max: Timestamp @fdc_generated(from: "Invitation.expiresAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "Invitation.id", purpose: GLOBAL_ID)
}
extend type MinecraftServer {
  """
  ✨ List `Invitation` objects in a one-to-many relationship (where `Invitation`.`server` is this object).
  """
  invitations_on_server(
    """
    Filter condition to narrow down the query results.
    """
    where: Invitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Invitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Invitation_Having
  ): [Invitation!]! @fdc_generated(from: "Invitation.server", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `ServerAccess` objects in a one-to-many relationship (where `ServerAccess`.`server` is this object).
  """
  serverAccesses_on_server(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerAccess_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerAccess_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerAccess_Having
  ): [ServerAccess!]! @fdc_generated(from: "ServerAccess.server", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `ServerLog` objects in a one-to-many relationship (where `ServerLog`.`server` is this object).
  """
  serverLogs_on_server(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerLog_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerLog_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerLog_Having
  ): [ServerLog!]! @fdc_generated(from: "ServerLog.server", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `User` objects using `ServerAccess` as the join table (a `ServerAccess` object exists where its `server` is this and its `user` is that).
  """
  users_via_ServerAccess(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerAccess_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerAccess_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerAccess_Having
  ): [User!]! @fdc_generated(from: "ServerAccess", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "MinecraftServer", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `MinecraftServer` table.
  """
  _count: Int! @fdc_generated(from: "MinecraftServer.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `gameMode` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  gameMode_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.gameMode", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `ipAddress` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ipAddress_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.ipAddress", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `maxPlayers` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  maxPlayers_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.maxPlayers", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `minecraftVersion` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  minecraftVersion_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.minecraftVersion", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `name` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  name_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.name", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `ownerId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  ownerId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.ownerId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `port` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  port_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.port", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `serverId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  serverId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.serverId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `serverSoftware` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  serverSoftware_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.serverSoftware", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `MinecraftServer` table where the `status` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  status_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "MinecraftServer.status", purpose: QUERY_COUNT)
  """
  ✨ Sum the `maxPlayers` field in the `MinecraftServer` table.
  """
  maxPlayers_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "MinecraftServer.maxPlayers", purpose: QUERY_SUM)
  """
  ✨ Sum the `port` field in the `MinecraftServer` table.
  """
  port_sum(
    """
    Set to true to sum the distinct values.
    """
    distinct: Boolean = false
  ): Int @fdc_generated(from: "MinecraftServer.port", purpose: QUERY_SUM)
  """
  ✨ Average the `maxPlayers` field in the `MinecraftServer` table.
  """
  maxPlayers_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "MinecraftServer.maxPlayers", purpose: QUERY_AVG)
  """
  ✨ Average the `port` field in the `MinecraftServer` table.
  """
  port_avg(
    """
    Set to true to average the distinct values.
    """
    distinct: Boolean = false
  ): Float @fdc_generated(from: "MinecraftServer.port", purpose: QUERY_AVG)
  """
  ✨ Minimum of the `createdAt` field in the `MinecraftServer` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "MinecraftServer.createdAt", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `maxPlayers` field in the `MinecraftServer` table.
  """
  maxPlayers_min: Int @fdc_generated(from: "MinecraftServer.maxPlayers", purpose: QUERY_MIN)
  """
  ✨ Minimum of the `port` field in the `MinecraftServer` table.
  """
  port_min: Int @fdc_generated(from: "MinecraftServer.port", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `MinecraftServer` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "MinecraftServer.createdAt", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `maxPlayers` field in the `MinecraftServer` table.
  """
  maxPlayers_max: Int @fdc_generated(from: "MinecraftServer.maxPlayers", purpose: QUERY_MAX)
  """
  ✨ Maximum of the `port` field in the `MinecraftServer` table.
  """
  port_max: Int @fdc_generated(from: "MinecraftServer.port", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "MinecraftServer.id", purpose: GLOBAL_ID)
}
extend type ServerAccess {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ServerAccess", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ServerAccess` table.
  """
  _count: Int! @fdc_generated(from: "ServerAccess.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerAccess` table where the `assignedAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  assignedAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerAccess.assignedAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerAccess` table where the `role` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  role_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerAccess.role", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerAccess` table where the `serverId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  serverId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerAccess.serverId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerAccess` table where the `userId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  userId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerAccess.userId", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `assignedAt` field in the `ServerAccess` table.
  """
  assignedAt_min: Timestamp @fdc_generated(from: "ServerAccess.assignedAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `assignedAt` field in the `ServerAccess` table.
  """
  assignedAt_max: Timestamp @fdc_generated(from: "ServerAccess.assignedAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ServerAccess.userId,serverId", purpose: GLOBAL_ID)
}
extend type ServerLog {
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "ServerLog", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `ServerLog` table.
  """
  _count: Int! @fdc_generated(from: "ServerLog.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerLog` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerLog.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerLog` table where the `level` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  level_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerLog.level", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerLog` table where the `message` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  message_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerLog.message", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerLog` table where the `serverId` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  serverId_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerLog.serverId", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `ServerLog` table where the `timestamp` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  timestamp_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "ServerLog.timestamp", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `timestamp` field in the `ServerLog` table.
  """
  timestamp_min: Timestamp @fdc_generated(from: "ServerLog.timestamp", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `timestamp` field in the `ServerLog` table.
  """
  timestamp_max: Timestamp @fdc_generated(from: "ServerLog.timestamp", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "ServerLog.id", purpose: GLOBAL_ID)
}
extend type User {
  """
  ✨ List `Invitation` objects in a one-to-many relationship (where `Invitation`.`invitedBy` is this object).
  """
  invitations_on_invitedBy(
    """
    Filter condition to narrow down the query results.
    """
    where: Invitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Invitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Invitation_Having
  ): [Invitation!]! @fdc_generated(from: "Invitation.invitedBy", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `Invitation` objects in a one-to-many relationship (where `Invitation`.`invitedTo` is this object).
  """
  invitations_on_invitedTo(
    """
    Filter condition to narrow down the query results.
    """
    where: Invitation_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [Invitation_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: Invitation_Having
  ): [Invitation!]! @fdc_generated(from: "Invitation.invitedTo", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `MinecraftServer` objects in a one-to-many relationship (where `MinecraftServer`.`owner` is this object).
  """
  minecraftServers_on_owner(
    """
    Filter condition to narrow down the query results.
    """
    where: MinecraftServer_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [MinecraftServer_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: MinecraftServer_Having
  ): [MinecraftServer!]! @fdc_generated(from: "MinecraftServer.owner", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `ServerAccess` objects in a one-to-many relationship (where `ServerAccess`.`user` is this object).
  """
  serverAccesses_on_user(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerAccess_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerAccess_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerAccess_Having
  ): [ServerAccess!]! @fdc_generated(from: "ServerAccess.user", purpose: QUERY_MULTIPLE_ONE_TO_MANY)
  """
  ✨ List `MinecraftServer` objects using `ServerAccess` as the join table (a `ServerAccess` object exists where its `user` is this and its `server` is that).
  """
  minecraftServers_via_ServerAccess(
    """
    Filter condition to narrow down the query results.
    """
    where: ServerAccess_Filter

    """
    Order the query results by specific fields.
    """
    orderBy: [ServerAccess_Order!]

    """
    Number of rows to skip before starting to return the results.
    """
    offset: Int

    """
    Maximum number of rows to return (defaults to 100 rows).
    """
    limit: Int = 100

    """
    Set to true to return distinct results.
    """
    distinct: Boolean = false

    """
    Filter condition to apply to the groups of aggregate queries.
    """
    having: ServerAccess_Having
  ): [MinecraftServer!]! @fdc_generated(from: "ServerAccess", purpose: QUERY_MULTIPLE_MANY_TO_MANY)
  """
  Implicit metadata field that cannot be written. It provides extra information about query results.
  """
  _metadata: _Metadata @fdc_generated(from: "User", purpose: METADATA_FIELD)
  """
  ✨ Count the number of rows in the `User` table.
  """
  _count: Int! @fdc_generated(from: "User.", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `createdAt` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  createdAt_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.createdAt", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `displayName` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  displayName_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.displayName", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `email` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  email_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.email", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `id` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  id_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.id", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `photoUrl` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  photoUrl_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.photoUrl", purpose: QUERY_COUNT)
  """
  ✨ Count the number of rows in the `User` table where the `username` field is non-null. Pass the `distinct` argument to instead count the number of distinct values.
  """
  username_count(
    """
    Set to true to count the number of distinct values.
    """
    distinct: Boolean = false
  ): Int! @fdc_generated(from: "User.username", purpose: QUERY_COUNT)
  """
  ✨ Minimum of the `createdAt` field in the `User` table.
  """
  createdAt_min: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MIN)
  """
  ✨ Maximum of the `createdAt` field in the `User` table.
  """
  createdAt_max: Timestamp @fdc_generated(from: "User.createdAt", purpose: QUERY_MAX)
  """
  A generated field that is used for caching results in SDKs.
  """
  _id: ID! @fdc_generated(from: "User.id", purpose: GLOBAL_ID)
}
